### ISSUE TITLE
Präsentation erstellen

### ISSUE THREAD

**Issue by JustABunchOfCode** [ob-algdatii-ss18/leistungsnachweis-b-team#18]
Wer macht was?

**Comment by micansid** [comment]
- B-Baum allgemein, Logik, Einsatzgebiet - Wolfgang
- C++ Lambda, Templates - Raphi
- B-Baum Entwicklung, am Beispiel generierter Dot-Files - Michi
- Vergleich mit Linked-List - Matthias
